//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pianoforte.Sena.Lang.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pianoforte.Sena.Lang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cannot conevrt {0} to {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotConvertType {
            get {
                return ResourceManager.GetString("CannotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot add {0} and {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidAddition {
            get {
                return ResourceManager.GetString("InvalidAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid character &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid escape sequence. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} SyntaxError -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyntaxExceptionMessage {
            get {
                return ResourceManager.GetString("SyntaxExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object {0} has not member {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefinedMember {
            get {
                return ResourceManager.GetString("UndefinedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined variables &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefinedVariable {
            get {
                return ResourceManager.GetString("UndefinedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown symobl &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnknownSymbol {
            get {
                return ResourceManager.GetString("UnknownSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unterminated string literal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("UnterminatedStringLiteral", resourceCulture);
            }
        }
    }
}
