[package]
name = "Solfege"
version = "0.1.0"
authors = ["z@kuro <z@kuro.red>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
