//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pianoforte.Solfege.Lang.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pianoforte.Solfege.Lang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cannot conevrt {0} to {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotConvertType {
            get {
                return ResourceManager.GetString("CannotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot devide by zero に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DevideByZero {
            get {
                return ResourceManager.GetString("DevideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;..&quot; is unknown syntax. Mistype of  &quot;...&quot; ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DotDotToken {
            get {
                return ResourceManager.GetString("DotDotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index, {0}, is out of array range に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot add {0} and {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidAddition {
            get {
                return ResourceManager.GetString("InvalidAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid character &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot devide {0} by {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDivision {
            get {
                return ResourceManager.GetString("InvalidDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid escape sequence. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left of assignment must be identifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidLeftOfAssignment {
            get {
                return ResourceManager.GetString("InvalidLeftOfAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot get length of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot multiply {0} by {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidMultiplication {
            get {
                return ResourceManager.GetString("InvalidMultiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Function requires {0} args, but passed {1} args に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidNumberOfArgs {
            get {
                return ResourceManager.GetString("InvalidNumberOfArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot repeat {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRepeat {
            get {
                return ResourceManager.GetString("InvalidRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot reverse {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidReverse {
            get {
                return ResourceManager.GetString("InvalidReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot slice {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidSlice {
            get {
                return ResourceManager.GetString("InvalidSlice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot subtract {1} from {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidSubtraction {
            get {
                return ResourceManager.GetString("InvalidSubtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is required but found {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot use negative value as length of array に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NegativeLength {
            get {
                return ResourceManager.GetString("NegativeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index access is array only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NonArrayIndexAccess {
            get {
                return ResourceManager.GetString("NonArrayIndexAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot apply not to non bool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NonBoolNot {
            get {
                return ResourceManager.GetString("NonBoolNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calli is only function に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NonFunctionCalling {
            get {
                return ResourceManager.GetString("NonFunctionCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index of array must be integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NonIntArrayIndex {
            get {
                return ResourceManager.GetString("NonIntArrayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot devide by non number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NonNumberDivision {
            get {
                return ResourceManager.GetString("NonNumberDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot use &quot;to&quot; with non number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NonNumberRange {
            get {
                return ResourceManager.GetString("NonNumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Member access is allowed only objects. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NonObjectMemberAccess {
            get {
                return ResourceManager.GetString("NonObjectMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot repeat by non number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepeatByNonNunmber {
            get {
                return ResourceManager.GetString("RepeatByNonNunmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RuntimeError {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RuntimeError {
            get {
                return ResourceManager.GetString("RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot slice by non number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SliceByNonNumber {
            get {
                return ResourceManager.GetString("SliceByNonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot step be zero に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StepIsZero {
            get {
                return ResourceManager.GetString("StepIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SyntaxErrror at {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} SyntaxError -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyntaxExceptionMessage {
            get {
                return ResourceManager.GetString("SyntaxExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object {0} has not member {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefinedMember {
            get {
                return ResourceManager.GetString("UndefinedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined variables &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefinedVariable {
            get {
                return ResourceManager.GetString("UndefinedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected token {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown symobl &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnknownSymbol {
            get {
                return ResourceManager.GetString("UnknownSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unterminated string literal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("UnterminatedStringLiteral", resourceCulture);
            }
        }
    }
}
